apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksdemo-5421"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksdemo-5421"
  template:
    metadata:
      labels:
        app: "aksdemo-5421"
    spec:
      containers:
        - name: "aksdemo-5421"
          image: "acrdemo111.azurecr.io/aksdemo"
          ports:
          - containerPort: 80